name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release-config:
    name: Release @trezy-studios/eslint-config
    uses: ./.github/workflows/release-base.yml
    with:
      packageName: '@trezy-studios/eslint-config'
    secrets: inherit

  release-config-electron:
    name: Release @trezy-studios/eslint-config-electron
    uses: ./.github/workflows/release-base.yml
    with:
      packageName: '@trezy-studios/eslint-config-electron'
    secrets: inherit

  release-config-react:
    name: Release @trezy-studios/eslint-config-react
    uses: ./.github/workflows/release-base.yml
    with:
      packageName: '@trezy-studios/eslint-config-react'
    secrets: inherit
